config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://localhost:8080'
  phases:
    -duration: 20
     arrivalRate: 10
scenarios:
  -name: 'Login  + register'
  flow:
    -log: 'Comienza secuencia un usuario'
    -get:
      url: '/create-user'
      capture:
        -json: "$.firstName"
          as: "firstName"
        -json: "$.lastName"
          as: "lasttName"
        -json: "$.email"
          as: "email"
        -json: "$.passworld"
          as: "passworld"

  -post:
    url:  '/api/session/register'
    json: 
      firstName:  "{{firstName}}"
      lasttName:  "{{lasttName}}"
      email:  "{{email}}"
      passworld:  "{{passworld}}"
  -think: 5
  -post:
    url:  '/api/session/login'
    json:
      email:  "{{email}}"
      passworld:  "{{passworld}}"

